"""add_login_tokens

Revision ID: f01457e6f4d8
Revises: f439417fc126
Create Date: 2026-03-28 08:19:20.980953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01457e6f4d8'
down_revision: Union[str, None] = 'f439417fc126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('login_tokens',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('client_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_tokens_client_id'), 'login_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_login_tokens_token'), 'login_tokens', ['token'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_tokens_token'), table_name='login_tokens')
    op.drop_index(op.f('ix_login_tokens_client_id'), table_name='login_tokens')
    op.drop_table('login_tokens')
    # ### end Alembic commands ###
