"""add_admin_notes_to_trips

Revision ID: f439417fc126
Revises: 7dc3b38520a2
Create Date: 2026-03-28 07:39:38.015720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f439417fc126'
down_revision: Union[str, None] = '7dc3b38520a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('admin_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'admin_notes')
    # ### end Alembic commands ###
